# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchecksys',
            name='psef',
        ),
        migrations.AddField(
            model_name='userchecksys',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='故障描述'),
        ),
    ]
