# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20180311_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckdev',
            name='checkdatabase',
        ),
        migrations.RemoveField(
            model_name='usercheckdev',
            name='checkmiddleware',
        ),
        migrations.AddField(
            model_name='usercheckdev',
            name='service',
            field=models.IntegerField(choices=[(1, '正常'), (2, '故障')], default=1, verbose_name='服务和进程状态'),
        ),
    ]
