# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-25 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20180925_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='巡检人')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='巡检时间')),
                ('ckeckCPU', models.CharField(max_length=50, verbose_name='CPU占用率（%）')),
                ('checkMEM', models.CharField(max_length=50, verbose_name='内存使用率(%)')),
                ('checkSessionNum', models.CharField(max_length=50, verbose_name='会话连接数')),
                ('state', models.IntegerField(choices=[(1, '正常'), (2, '故障')], default=1, verbose_name='设备状态')),
                ('details', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('Sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.SecurityDevice', verbose_name='安全设备')),
            ],
            options={
                'verbose_name_plural': '安全设备巡检信息',
                'ordering': ['-add_time'],
                'verbose_name': '安全设备巡检信息',
            },
        ),
    ]
