# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-26 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_userchecksec'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NetworkDevice_name', models.CharField(max_length=50, verbose_name='网络设备名称')),
                ('NetworkDevice_IP', models.GenericIPAddressField(verbose_name='IP地址')),
                ('SecurityDevice_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='巡检账号')),
                ('SecurityDevice_pwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='巡检密码')),
                ('auto_check', models.IntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='安全设备是否进行自动巡检')),
            ],
            options={
                'verbose_name_plural': '网络设备信息',
                'verbose_name': '网络设备信息',
            },
        ),
        migrations.CreateModel(
            name='UserCheckNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='巡检人')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='巡检时间')),
                ('UpstreamBandwidth', models.CharField(blank=True, max_length=50, null=True, verbose_name='上行带宽')),
                ('DownstreamBandwidth', models.CharField(blank=True, max_length=50, null=True, verbose_name='下行带宽')),
                ('details', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('Net_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.NetworkDevice', verbose_name='网络设备')),
            ],
            options={
                'verbose_name_plural': '网络设备巡检信息',
                'ordering': ['-add_time'],
                'verbose_name': '网络设备巡检信息',
            },
        ),
        migrations.CreateModel(
            name='UserCheckNetSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='巡检人')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='巡检时间')),
                ('CoreSwitch', models.TextField(verbose_name='核心交换机状态')),
                ('ConvergingSwitch', models.TextField(verbose_name='汇聚交换机状态')),
                ('details', models.TextField(blank=True, null=True, verbose_name='无线设备状态')),
                ('Net_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.NetworkDevice', verbose_name='网络设备')),
            ],
            options={
                'verbose_name_plural': '网络设备总体巡检信息',
                'ordering': ['-add_time'],
                'verbose_name': '网络设备总体巡检信息',
            },
        ),
    ]
