# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-29 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_remove_userchecknetsys_net_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchecksys',
            name='check_details',
            field=models.TextField(blank=True, null=True, verbose_name='故障描述'),
        ),
    ]
